# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', ecommapp.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Availibilty_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_Category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Product_Belongs_To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_First_Name', models.CharField(max_length=100)),
                ('Customer_Last_Name', models.CharField(max_length=100)),
                ('Customer_Email', models.CharField(max_length=100)),
                ('Address_Line1', models.CharField(max_length=200)),
                ('Address_Line2', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('ZIP', models.IntegerField()),
                ('Volts_Credit', models.IntegerField(default=0)),
                ('User_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Card_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('Owner', models.CharField(max_length=50)),
                ('Date_Of_Expiry', models.DateField()),
                ('CVV', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('Card_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Id', models.CharField(max_length=200)),
                ('Order_Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Order_Address_Line1', models.CharField(max_length=200)),
                ('Order_Address_Line2', models.CharField(max_length=200)),
                ('Order_City', models.CharField(max_length=200)),
                ('Order_State', models.CharField(max_length=200)),
                ('Order_ZIP', models.IntegerField()),
                ('Order_Volts_Credit', models.IntegerField(default=0)),
                ('Order_Contact_Number', models.IntegerField()),
                ('Order_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Customer')),
                ('Order_Delivery_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Delivery_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product_Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Transaction_Id', models.CharField(max_length=100, unique=True)),
                ('Invoice_Id', models.CharField(max_length=100, unique=True)),
                ('Invoice', models.FileField(upload_to='Invoices/')),
                ('Esimated_Dilivery_Date', models.DateField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_for_order', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('Images', models.ImageField(upload_to='ProductImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=200)),
                ('Product_Code', models.TextField(max_length=100, unique=True)),
                ('Price', models.FloatField()),
                ('Description', models.TextField(max_length=10000)),
                ('Features', models.TextField(max_length=10000)),
                ('TechnicalSpecs', models.CharField(max_length=10000)),
                ('color', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Title', models.CharField(max_length=200)),
                ('Review_Body', models.TextField(max_length=5000)),
                ('Product_Rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product')),
                ('Reviwer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales_First_Name', models.CharField(max_length=100)),
                ('Sales_Last_Name', models.CharField(max_length=100)),
                ('Sales_Email', models.CharField(max_length=100)),
                ('Sales_Person_UCode', models.CharField(max_length=100)),
                ('is_intern', models.BooleanField(default=False)),
                ('Sales_Contact_Number', models.IntegerField()),
                ('Sales_Points', models.IntegerField(default=0)),
                ('Sales_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Id', models.CharField(max_length=100, unique=True)),
                ('Seller_Name', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=500)),
                ('Profile', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('Contact_Number', models.IntegerField()),
                ('Seller_Rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_Company_Name', models.CharField(max_length=100)),
                ('Shipping_Company_Id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category', models.CharField(max_length=100, unique=True)),
                ('Base_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.BaseCategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Availiability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product_Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='Produce_Base_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.BaseCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.SubCategory'),
        ),
        migrations.AddField(
            model_name='pics',
            name='ProductPics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Payment_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Payment_Method'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Payment_Status'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order_Status_Model'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Ordered_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Shipment_Authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Shipment_Orgs'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='Product_In_Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Customer'),
        ),
    ]
