# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='Base_Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Filter',
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_State',
            field=models.CharField(max_length=200),
        ),
    ]
