# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flash_sale',
            name='Main_Flash_Sale_Banner',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='Seller_Rating',
        ),
    ]
