# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='Sub_Category_Slug',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Sub_Category_Slug_Field',
            field=models.SlugField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='basecategory',
            name='Base_Slug_Field',
            field=models.SlugField(default='', max_length=120, unique=True),
        ),
    ]
