# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter_Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='filter_category',
            name='Filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Filter_Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Filter',
            field=models.ManyToManyField(to='ecommapp.Filter_Category'),
        ),
    ]
