# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Sub_Category',
            field=models.CharField(max_length=100),
        ),
    ]
