# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='credits_used',
            field=models.IntegerField(default=0),
        ),
    ]
