# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20170906_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategory',
            name='Base_Slug_Field',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Sub_Category_Slug_Field',
            field=models.SlugField(default=True, max_length=120),
        ),
    ]
