# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20170903_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flash_Sale_Name', models.CharField(max_length=100)),
                ('Products_In_Sale', models.ManyToManyField(to='ecommapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_price',
            field=models.FloatField(default=0),
        ),
    ]
