# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20171002_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_name',
            name='Filter_Subcategory_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.SubCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='Whole_Order_Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order_Status_Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='TaxOnProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Tax'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='Sales_Member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
    ]
