# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_auto_20171105_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Seller',
        ),
    ]
