# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_auto_20171013_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomerCouponUsedTrack',
            new_name='CustomerCouponUsed',
        ),
        migrations.RemoveField(
            model_name='flash_sale_banner',
            name='Flash_Sale_Ancess',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Reviewer',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-Order_Date_Time']},
        ),
        migrations.RenameField(
            model_name='customercouponused',
            old_name='customer',
            new_name='customer_track',
        ),
        migrations.RenameField(
            model_name='order_product_specs',
            old_name='Shipment_Authority',
            new_name='Shipment_Authority_Details',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='Flash_slug',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Order_Reference',
        ),
        migrations.RemoveField(
            model_name='shipment_orgs',
            name='Shipping_Company_Id',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.CouponCode'),
        ),
        migrations.AddField(
            model_name='customer',
            name='usability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='Flash_Sale_URL',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Shipment_Id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment_orgs',
            name='Shipping_Company_URL',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filter_name',
            name='Filter_Subcategory_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.SubCategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Whole_Order_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order_Status_Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='TaxOnProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Tax'),
        ),
        migrations.DeleteModel(
            name='Flash_Sale_Banner',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order'),
        ),
    ]
