# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_auto_20171225_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Payment_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
