# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_auto_20171125_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='CustomImages/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Whole_Order_Status',
        ),
    ]
