# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_remove_product_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Join_Date_Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
