# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_auto_20171126_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_pic',
            field=models.ImageField(default='', upload_to='BrandPic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
