# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_auto_20170908_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='Is_Main_Image',
        ),
        migrations.RemoveField(
            model_name='pics',
            name='is_Thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='Main_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ProductImages/'),
            preserve_default=False,
        ),
    ]
