# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_order_order_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='Invoice_visible',
            field=models.BooleanField(default=False),
        ),
    ]
