# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_auto_20170908_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flash_sale_banner',
            old_name='Banner_Pic',
            new_name='Banner_Pics',
        ),
        migrations.RemoveField(
            model_name='flash_sale_banner',
            name='Is_Main_Banner',
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='Main_Banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='FlashSaleBanner/'),
            preserve_default=False,
        ),
    ]
