# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_auto_20170908_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='Is_Detail_Image',
        ),
    ]
