# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_auto_20171126_2228'),
        ('ecommapp', '0004_customer_join_date_time'),
    ]

    operations = [
    ]
