# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_merge_20171127_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='Prducts',
            new_name='Products',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Join_Date_Time',
        ),
        migrations.AddField(
            model_name='customer',
            name='can_create_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Features',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='TechnicalSpecs',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
