# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_auto_20171127_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModulePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='CustomWorkImages/')),
                ('preview', models.ImageField(upload_to='CustomWorkImages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product')),
            ],
        ),
    ]
