# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_auto_20170910_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
