# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_custommodulepics'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodulepics',
            name='text_to_be_inserted',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
