# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0010_custommodulepics_text_to_be_inserted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodulepics',
            name='text_to_be_inserted',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
