# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0010_auto_20170910_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Product_In_Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product'),
        ),
        migrations.AlterField(
            model_name='order_product_specs',
            name='Order_Reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AlterField(
            model_name='order_product_specs',
            name='Ordered_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Product'),
        ),
    ]
