# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0011_auto_20171201_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Invoice',
            field=models.FileField(null=True, upload_to='Invoices/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Sub_Caegory_alias',
            field=models.CharField(default='sub', max_length=20),
        ),
    ]
