# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0012_auto_20171202_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Sub_Caegory_alias',
            new_name='Sub_Category_alias',
        ),
    ]
