# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0013_remove_sales_team_sales_person_ucode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Wishlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
