# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0014_typeofcustomproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.TypeOfCustomProduct'),
        ),
    ]
