# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0015_wish_list_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Contact_Number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
