# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0015_brand_brand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='Sales_Member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
    ]
