# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0016_auto_20171202_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Join_Date_Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
