# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0016_customer_customer_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoupounApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupoun_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.CouponCode')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Customer')),
            ],
        ),
    ]
