# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0017_customercoupounapplied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerCoupounApplied',
            new_name='CustomerCouponUsedTrack',
        ),
        migrations.RenameField(
            model_name='customercouponusedtrack',
            old_name='coupoun_code',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='order_product_specs',
            old_name='Esimated_Dilivery_Date',
            new_name='Esimated_Delivery_Date',
        ),
        migrations.RenameField(
            model_name='order_product_specs',
            old_name='Order_price',
            new_name='Final_Ordered_Product_price',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Reviwer',
            new_name='Reviewer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Contact_Number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_Volts_Credit',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Invoice_Id',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Order_Payment_Type',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Order_Payment_status',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Order_Reference',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Transaction_Id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coupoun_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.CouponCode'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='Discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_In_Name_Of',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Payment_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Payment_Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Payment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Payment_Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AddField(
            model_name='order',
            name='Transaction_Id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Volts_Credit_Used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Shipment_Authority',
            field=models.ManyToManyField(to='ecommapp.Shipment_Orgs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_State',
            field=models.CharField(default='DelhiNCR', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availiability',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Product_Status',
        ),
    ]
