# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0017_customer_join_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreturn',
            name='Order',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Order_Product_Specs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='Reason',
            field=models.CharField(default='asdadfs', max_length=100),
            preserve_default=False,
        ),
    ]
