# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0018_auto_20170926_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash_sale',
            name='Flash_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
