# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0019_flash_sale_flash_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coupoun_code',
            new_name='coupon_code',
        ),
    ]
