# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0020_auto_20170926_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Transaction_Id',
            field=models.CharField(max_length=100),
        ),
    ]
