# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0021_auto_20170926_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.CouponCode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
    ]
