# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0023_auto_20170926_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_Reference',
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Order_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AlterField(
            model_name='order_product_specs',
            name='Final_Ordered_Product_price',
            field=models.FloatField(),
        ),
    ]
