# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0024_auto_20170926_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Esimated_Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Filter',
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_State',
            field=models.CharField(max_length=200),
        ),
    ]
