# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0026_auto_20170930_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Produce_Base_Category',
            new_name='Product_Base_Category',
        ),
    ]
