# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0030_filter_name_filter_subcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='Code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flash_sale',
            name='Flash_slug',
            field=models.SlugField(blank=True),
        ),
    ]
