# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0031_auto_20171012_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
