# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0033_seller_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_user',
        ),
    ]
