# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0036_auto_20171019_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerCouponUsedTrack',
            new_name='CustomerCouponUsed',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-Order_Date_Time']},
        ),
        migrations.RenameField(
            model_name='customercouponused',
            old_name='customer',
            new_name='customer_track',
        ),
        migrations.RenameField(
            model_name='order_product_specs',
            old_name='Shipment_Authority',
            new_name='Shipment_Authority_Details',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order_product_specs',
            name='Order_Reference',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.CouponCode'),
        ),
        migrations.AddField(
            model_name='customer',
            name='usability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommapp.Sales_Team'),
        ),
        migrations.AddField(
            model_name='order_product_specs',
            name='Shipment_Id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
